---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present
      tags:
        - docker

    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - docker

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
      tags:
        - docker

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
      tags:
        - docker

    - name: Add Docker repository to apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      tags:
        - docker

    - name: Update apt package index after adding Docker repository
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      tags:
        - docker

    - name: Add user to docker group
      user:
        name: adminuser
        groups: docker
        append: yes
      tags:
        - docker

    # - name: Install docker-compose
    #   remote_user: ubuntu
    #   get_url:
    #     url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    #     dest: "/usr/local/bin/docker-compose"
    #     mode: "0755"
    #   tags:
    #     - docker

    # - name: Create symbolic link for docker-compose
    #   remote_user: ubuntu
    #   command: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    #   tags:
    #     - docker

    # - name: Show docker-compose version
    #   remote_user: ubuntu
    #   command: /usr/local/bin/docker-compose --version
    #   register: docker_compose_version
    #   tags:
    #     - docker

    # - name: Print docker-compose version
    #   debug:
    #     msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
    #   tags:
    #     - docker