name: packer build
on:
  push:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/aws-docker-ubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/aws-docker-ubuntu.pkr.hcl"