name: packer build
on:
  push:
    branches:
      - main

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/aws-docker-ubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          pwd
          ls -la
          packer validate \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" \
            ./packer/aws-docker-ubuntu.pkr.hcl